# Generated by Django 3.2.9 on 2021-11-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
