# Generated by Django 3.2.9 on 2021-12-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_student_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_student_prog',
            field=models.ForeignKey(default='n/a', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.programme'),
        ),
    ]
