# Generated by Django 3.2.9 on 2021-12-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211211_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_student_prog',
        ),
    ]
